name: gotrack
channels:
  - defaults
  - pytorch
  - nvidia
  - xformers
  - conda-forge
dependencies:
  - python=3.10
  - pytorch::pytorch=2.0.0
  - pytorch::pytorch-cuda=11.7.0 # GPU
  - pytorch::torchvision
  - omegaconf
  - torchmetrics=0.10.3
  - fvcore
  - iopath
  - torchinfo
  - omegaconf
  - cython
  - faiss-gpu=1.8.0 # GPU
  - scipy=1.13.0
  - kiwisolver=1.3.1
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pillow=10.3.0
  - pip=24.0
  - vispy=0.12.1
  - einops
  - distinctipy
  - trimesh
  - pip=24.0
  - pip:
    - cython==3.0.10
    - ultralytics==8.0.135
    - xformers==0.0.20 # GPU
    - git+https://github.com/facebookincubator/submitit
    - --extra-index-url https://pypi.nvidia.com
    - cuml-cu11==23.04 # GPU
    - --extra-index-url https://pypi.nvidia.com
    - kornia==0.7.2
    - pypng==0.20220715.0
    - glumpy==1.2.1
    - pycocotools==2.0
    - scikit-learn==1.5.0
    - scikit-image==0.22.0
    - imageio==2.34.1
    - pyopengl==3.1.0
    - pyglet==2.0.15
    - pytz==2024.1
    - pyrender==0.1.45
    - webdataset==0.2.86
    - git+https://github.com/facebookresearch/hand_tracking_toolkit
    - opencv-python
    - pytorch-lightning==1.8.6
    - hydra-colorlog==1.2.0
    - hydra-core==1.3.2
    - ultralytics==8.0.135
    - huggingface-hub